const QUERIES = {
    PERMISSIONS_LIST: 'permissions-list',
    ROLES_LIST: 'roles-list',
    USERS_LIST: 'users-list',
    CATEGORIES_LIST: 'categories-list',
    CITIES_LIST: 'cities-list',
    COUNTRIES_LIST: 'countries-list',
    PAYMENT_METHODS_LIST: 'payment-methods-list',
    TAGS_LIST: 'tags-list',
    COLLECTIONS_LIST: 'collections-list',
    CLAIMS_LIST: 'claims-list',
    INGREDIENTS_LIST: 'ingredients-list',
    LIFESTYLE_LIST: 'lifestyles-list',
    HIGHLIGHT_LIST: 'highlights-list',
    NUTRITIONAL_ATTRIBUTES_LIST: 'nutritional-attributes-list',
    PRODUCTS_LIST: 'products-list',
    DISCOUNT_CODES_LIST: 'discount-codes-list',
    ORDERS_LIST: 'orders-list',
    COMMERCE_GUEST_CUSTOMERS_LIST: 'commerce-guest-customers-list',
    COMMERCE_ACTIVE_CUSTOMERS_LIST: 'commerce-active-customers-list',
    COMMERCE_POTENTIAL_CUSTOMERS_LIST: 'commerce-potential-customers-list',
    CUSTOMERS_LIST: 'customers-list',
    CONTENT_SITE_LIST: 'content-site-list',
    CONTENT_RECIPES_LIST: 'content-recipes-list',
    CONTENT_BLOGS_LIST: 'content-blogs-list',
    CONTENT_FAQS_LIST: 'content-faqs-list',
    CONTENT_CUSTOMER_REVIEWS_LIST: 'content-customer-reviews-list',
    CONTENT_PROMOTIONAL_BANNERS_LIST: 'content-promotional-banners-list',
    ENGAGEMENT_REVIEWS_LIST: 'engagement-reviews-list',
    ENGAGEMENT_SUBSCRIPTIONS_LIST: 'engagement-subscriptions-list',
    ENGAGEMENT_GET_CODE_SUBMISSIONS_LIST: 'engagement-get-code-submissions-list',
    ENGAGEMENT_CONTACT_SUBMISSIONS_LIST: 'engagement-contact-submissions-list',
}

export {QUERIES}
